name: Build and Push Docker Image

on:
  push:
    branches:
      - master # Triggers on pushes to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t dharani2ddharan/nestjs-app:latest .

      - name: Push Docker Image
        run: |
          docker push dharani2ddharan/nestjs-app:latest
